### ISSUE TITLE
Componet Rendering issue

### ISSUE THREAD

**Issue by DayanandD** [Sidd444/Quiz-Whizz#1]
I have created footer component, but it is not rendering, i have done all the necessary ways but not working

**Comment by Sidd444** [comment]
The app is not running now , what is this mui material that you have imported?

**Comment by DayanandD** [comment]
it is material Ui library
npm install @mui/material @emotion/react @emotion/styled can resolve the issue
________________________________

**Comment by Sidd444** [comment]
ok I will look into it ,let me implement a few more backend features then we will move to the designing part
